---
apiVersion: v1
kind: Secret
metadata:
  name: my-db-password
data:
  password: T1QrOXZQcDhMdXhoeFVQWVpLSk1kUG1YM04xTzBTd3YzWG5ZVjI0UFZzcz0=
---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: my-db
  annotations:
    organization: DevOps Toolkit
    author: Viktor Farcic <viktor@farcic.com>
spec:
  id: my-db-20241019213440
  compositionSelector:
    matchLabels:
      provider: azure
      db: postgresql
  parameters:
    version: "11"
    size: small
