---
apiVersion: v1
kind: Secret
metadata:
  name: my-db-20241018201755-password
  namespace: crossplane-system
data:
  password: T1QrOXZQcDhMdXhoeFVQWVpLSk1kUG1YM04xTzBTd3YzWG5ZVjI0UFZzcz0=
---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQL
metadata:
  name: my-db-20241018201755
spec:
  compositionSelector:
    matchLabels:
      provider: azure
      db: postgresql
