---
apiVersion: v1
kind: Secret
metadata:
  name: my-db-20241018201756-password
  namespace: crossplane-system
data:
  password: T1QrOXZQcDhMdXhoeFVQWVpLSk1kUG1YM04xTzBTd3YzWG5ZVjI0UFZzcz0=
---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQL
metadata:
  name: my-db
  annotations:
    organization: DevOps Toolkit
    author: Viktor Farcic <viktor@farcic.com>
spec:
  id: my-db-20241018201756
  compositionSelector:
    matchLabels:
      provider: azure
      db: postgresql
  parameters:
    version: "11"
    size: small
